import { Box, Heading, Text, Image, Grid, useColorModeValue } from '@chakra-ui/react';
import FeatImage01 from '../../../assets/img/zigzag/feat-image-1.png';
import FeatImage02 from '../../../assets/img/zigzag/feat-image-2.png';
import FeatImage03 from '../../../assets/img/zigzag/feat-image-3.png';
import FeatImage04 from '../../../assets/img/zigzag/feat-image-4.png';

interface FeatureItemProps {
  imageSrc: string;
  altText: string;
  title: string;
  subtitle: string;
  description: string;
  reverse?: boolean;
}

const FeatureItem: React.FC<FeatureItemProps> = ({
  imageSrc,
  altText,
  title,
  subtitle,
  description,
  reverse,
}) => {
  const bgCard = useColorModeValue('darkbrading.50', 'lightbranding.100');
  const textCard = useColorModeValue('gray.400', 'darkbrading.500');
  
  return (
    <Grid
      templateColumns={{
        lg: 'repeat(12, 1fr)',
        sm: 'repeat(2, 1fr)',
        base: '1fr',
      }}
      gap={6}
      alignItems="center"
      flexDirection={reverse ? 'row-reverse' : 'row'}
      position="relative"
      overflow="hidden"
    >
      {/* Image Section */}
      <Box
        gridColumn={['1 / -1', 'span 6']}
        order={[1, 1, reverse ? 2 : 1]}
        display="flex"
        justifyContent="center"
        position="relative"
        zIndex={4}
      >
        <Image
          src={imageSrc}
          alt={altText}
          width="auto"
          height={300}
          borderRadius="md"
          objectFit="cover"
        />
      </Box>

      {/* Content Section */}
      <Box
        gridColumn={['1 / -1', 'span 6']}
        bg={bgCard}
        p={3}
        boxShadow="xl"
        position="relative"
        zIndex={2}
        height="min-content"
        width="fit-content"
        borderRadius='20'
        sx={{
          '@media screen and (min-width: 1024px)': {
            order: [2, 2, reverse ? 1 : 2],
            transform: reverse ? 'translateX(230px)' : 'translateX(-230px)',
            paddingLeft: reverse ? '15px' : '90px',
            paddingRight: reverse ? '90px' : '15px',
            borderRadius: reverse ? '20px 5px 5px 20px' : '5px 20px 20px 5px'
          },
        }}
      >
        <Box mb={4}>
          <Text
            fontSize="lg"
            fontWeight="bold"
            color="darkbrading.500"
            bg="lightbranding.50"
            display="inline-block"
            py="2px"
            px={3}
            borderRadius="full"
            mb={4}
          >
            {subtitle}
          </Text>
          <Heading size="sm" mb={1} color="lightbranding.500">
            {title}
          </Heading>
          <Text fontSize="md" mb={1} color={textCard}>
            {description}
          </Text>
        </Box>
      </Box>
    </Grid>
  );
};

export default function Zigzag() {
  return (
    <Box maxW="6xl" mx="auto" px={[4, 6]} py={[12, 20]} id="objectives">
      <Box textAlign="center" mb={12}>
        <Text
          fontSize="lg"
          fontWeight="bold"
          color="darkbrading.500"
          bg="lightbranding.50"
          display="inline-block"
          py="2px"
          px={3}
          borderRadius="full"
          mb={4}
        >
          Achieve Goals That Matter
        </Text>
        <Heading as="h1" size="xl" mb={4}>
          What Sets Us Apart?
        </Heading>
      </Box>

      <Grid gap={20}>
        <FeatureItem
          imageSrc={FeatImage01}
          altText="Feature 01"
          title=""
          subtitle="Experience and Deep Salesforce Knowledge"
          description="Our team is highly trained and certified in Salesforce, enabling us to deliver high-quality solutions that go beyond the standard."
        />

        <FeatureItem
          imageSrc={FeatImage02}
          altText="Feature 02"
          title=""
          subtitle="Custom Solutions for Each Client"
          description="We don’t believe in one-size-fits-all solutions. We take the time to understand your business and goals, creating solutions that truly impact your productivity and growth."
          reverse
        />

        <FeatureItem
          imageSrc={FeatImage03}
          altText="Feature 03"
          title=""
          subtitle="Customer-Centric Approach"
          description="Automatically distribute the information generated by the system within minutes, achieving complete and customized reports tailored to your business needs."
        />

        <FeatureItem
          imageSrc={FeatImage04}
          altText="Feature 04"
          title=""
          subtitle="Satisfied Clients"
          description="Leading companies like K2 and Sonos have trusted Santsoft for their Salesforce needs. Our personalized approach and measurable results have allowed us to build lasting relationships with our clients."
          reverse
        />
      </Grid>
    </Box>
  );
}
