# Usa Node.js 20.10.0 como base
FROM node:20.10.0

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de dependencias
COPY package.json package-lock.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos de tu proyecto
COPY . .

# Expone el puerto 4000
EXPOSE 4000

# Comando para iniciar la aplicación
CMD ["npm", "start"]